@base=localhost:8000
@auth=Basic root:root
@namespace=rollplayer
@database=main

###

POST {{base}}/sql
Authorization: {{auth}}
Accept: application/json
Surreal-NS: {{namespace}}
Surreal-DB: {{database}}
Content-Type: surql

select * from characters

###

POST {{base}}/sql
Authorization: {{auth}}
Accept: application/json
Surreal-NS: {{namespace}}
Surreal-DB: {{database}}
Content-Type: surql

delete characters

###

POST {{base}}/sql
Authorization: {{auth}}
Accept: application/json
Surreal-NS: {{namespace}}
Surreal-DB: {{database}}
Content-Type: surql

insert into characters {
    name: 'Bloodgrasp'
}

###

POST {{base}}/sql
Authorization: {{auth}}
Accept: application/json
Surreal-NS: {{namespace}}
Surreal-DB: {{database}}
Content-Type: surql

info for db
